// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etpsqphiihdyfwkhlsdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cHNxcGhpaWhkeWZ3a2hsc2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjI4NjAsImV4cCI6MjA2NDc5ODg2MH0.aWG264nTN6kPlnZrQjfD-29szvF8jsuPvMmdxk1Fpq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);